name: shop_mobx
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: 2.0.4
  flutter_mobx: 2.0.2
  dio: ^4.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  cached_network_image: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  auto_route: 2.0.0
  json_annotation: 4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: 2.0.2
  build_runner: ^2.1.2
  json_serializable: 4.1.4
  auto_route_generator: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/